In [1]:
'''
This program is RDPS + ML(SVM,RF)
Make by J.-H. Kang (2025.03)
Result : KIM-Rigional -> Frost
'''
import os
import glob
import pandas as pd
import numpy as np
import sys
import datetime
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import scipy.stats as stats
from sklearn.metrics import confusion_matrix
import pickle
from imblearn.over_sampling import BorderlineSMOTE


In [2]:
# 73 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)

# +all data -> one table

for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    print(Y_train)
    # Train data OverSampling

    smote = BorderlineSMOTE()
    X_train_new, Y_train_new = smote.fit_resample(X_train, Y_train)
    nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
    nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
    print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

    scaler1 = MinMaxScaler()
    scaler1.fit(X_train_new)
    X_train_new = scaler1.transform(X_train_new)
    # save dataset (pickle files)

    output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/73class'

    with open(f'{output_path}/X_train_T{i}.pkl','wb') as f1:
       pickle.dump(X_train_new, f1)
    with open(f'{output_path}/Y_train_T{i}.pkl','wb') as f2:
       pickle.dump(Y_train_new, f2)
    with open(f'{output_path}/scaler_T{i}.pkl','wb') as f5:
       pickle.dump(scaler1, f5)

[0. 1. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5679), Frost 1(5679)
[0. 1. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5672), Frost 1(5672)
[0. 1. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5729), Frost 1(5729)
[0. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5759), Frost 1(5759)
[0. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5737), Frost 1(5737)
[1. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5683), Frost 1(5683)
[1. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5680), Frost 1(5680)
[1. 0. 1. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5673), Frost 1(5673)
[1. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5729), Frost 1(5729)
[0. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5759), Frost 1(5759)
[0. 0. 0. ... 0. 0. 0.]
Finish Oversampling, check to count: Frost 0(5737), Frost 1(5737)
[0. 0. 0. 

In [3]:
# 1 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)

# +all data -> one table

for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    # Train data OverSampling
    if i == 0:
        total_X = X_train
        total_Y = Y_train
    else:
        total_X = np.vstack((total_X,X_train))
        total_Y = np.hstack((total_Y,Y_train))

    
smote = BorderlineSMOTE()
X_train_new, Y_train_new = smote.fit_resample(total_X, total_Y)
nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

scaler1 = MinMaxScaler()
scaler1.fit(X_train_new)
X_train_new = scaler1.transform(X_train_new)
    # save dataset (pickle files)

output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/1class'

with open(f'{output_path}/X_train.pkl','wb') as f1:
    pickle.dump(X_train_new, f1)
with open(f'{output_path}/Y_train.pkl','wb') as f2:
    pickle.dump(Y_train_new, f2)
with open(f'{output_path}/scaler.pkl','wb') as f5:
    pickle.dump(scaler1, f5)

Finish Oversampling, check to count: Frost 0(416785), Frost 1(416785)


In [4]:
# 3 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)
output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/3class'
# +all data -> one table

cut_i = [0, 24, 48, 72]
j = 0
for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    # Train data OverSampling
    if i == cut_i[j]:
        total_X = X_train
        total_Y = Y_train
        j += 1
    else:
        total_X = np.vstack((total_X,X_train))
        total_Y = np.hstack((total_Y,Y_train))
        if i == cut_i[j]-1:
            smote = BorderlineSMOTE()
            X_train_new, Y_train_new = smote.fit_resample(total_X, total_Y)
            nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
            nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
            print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

            scaler1 = MinMaxScaler()
            scaler1.fit(X_train_new)
            X_train_new = scaler1.transform(X_train_new)
             # save dataset (pickle files)

            with open(f'{output_path}/X_train_T{j}.pkl','wb') as f1:
                pickle.dump(X_train_new, f1)
            with open(f'{output_path}/Y_train_T{j}.pkl','wb') as f2:
                pickle.dump(Y_train_new, f2)
            with open(f'{output_path}/scaler_T{j}.pkl','wb') as f5:
                pickle.dump(scaler1, f5)

Finish Oversampling, check to count: Frost 0(137057), Frost 1(137057)
Finish Oversampling, check to count: Frost 0(137035), Frost 1(137035)
Finish Oversampling, check to count: Frost 0(137013), Frost 1(137013)


In [5]:
# 6 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)
output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/6class'
# +all data -> one table

cut_i = [0, 12, 24, 36, 48, 60, 72]
j = 0
for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    # Train data OverSampling
    if i == cut_i[j]:
        total_X = X_train
        total_Y = Y_train
        j += 1
    else:
        total_X = np.vstack((total_X,X_train))
        total_Y = np.hstack((total_Y,Y_train))
        if i == cut_i[j]-1:
            smote = BorderlineSMOTE()
            X_train_new, Y_train_new = smote.fit_resample(total_X, total_Y)
            nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
            nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
            print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

            scaler1 = MinMaxScaler()
            scaler1.fit(X_train_new)
            X_train_new = scaler1.transform(X_train_new)
             # save dataset (pickle files)

            with open(f'{output_path}/X_train_T{j}.pkl','wb') as f1:
                pickle.dump(X_train_new, f1)
            with open(f'{output_path}/Y_train_T{j}.pkl','wb') as f2:
                pickle.dump(Y_train_new, f2)
            with open(f'{output_path}/scaler_T{j}.pkl','wb') as f5:
                pickle.dump(scaler1, f5)

Finish Oversampling, check to count: Frost 0(68521), Frost 1(68521)
Finish Oversampling, check to count: Frost 0(68536), Frost 1(68536)
Finish Oversampling, check to count: Frost 0(68516), Frost 1(68516)
Finish Oversampling, check to count: Frost 0(68519), Frost 1(68519)
Finish Oversampling, check to count: Frost 0(68493), Frost 1(68493)
Finish Oversampling, check to count: Frost 0(68520), Frost 1(68520)


In [7]:
# 12 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)
output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/12class'
# +all data -> one table

cut_i = [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72]
j = 0
for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    # Train data OverSampling
    if i == cut_i[j]:
        total_X = X_train
        total_Y = Y_train
        j += 1
    else:
        total_X = np.vstack((total_X,X_train))
        total_Y = np.hstack((total_Y,Y_train))
        if i == cut_i[j]-1:
            smote = BorderlineSMOTE()
            X_train_new, Y_train_new = smote.fit_resample(total_X, total_Y)
            nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
            nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
            print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

            scaler1 = MinMaxScaler()
            scaler1.fit(X_train_new)
            X_train_new = scaler1.transform(X_train_new)
             # save dataset (pickle files)

            with open(f'{output_path}/X_train_T{j}.pkl','wb') as f1:
                pickle.dump(X_train_new, f1)
            with open(f'{output_path}/Y_train_T{j}.pkl','wb') as f2:
                pickle.dump(Y_train_new, f2)
            with open(f'{output_path}/scaler_T{j}.pkl','wb') as f5:
                pickle.dump(scaler1, f5)

Finish Oversampling, check to count: Frost 0(34259), Frost 1(34259)
Finish Oversampling, check to count: Frost 0(34262), Frost 1(34262)
Finish Oversampling, check to count: Frost 0(34267), Frost 1(34267)
Finish Oversampling, check to count: Frost 0(34269), Frost 1(34269)
Finish Oversampling, check to count: Frost 0(34257), Frost 1(34257)
Finish Oversampling, check to count: Frost 0(34259), Frost 1(34259)
Finish Oversampling, check to count: Frost 0(34260), Frost 1(34260)
Finish Oversampling, check to count: Frost 0(34259), Frost 1(34259)
Finish Oversampling, check to count: Frost 0(34240), Frost 1(34240)
Finish Oversampling, check to count: Frost 0(34253), Frost 1(34253)
Finish Oversampling, check to count: Frost 0(34261), Frost 1(34261)
Finish Oversampling, check to count: Frost 0(34259), Frost 1(34259)


In [8]:
# 24 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)
output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/24class'
# +all data -> one table

cut_i = range(0,73,3)
j = 0
for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    # Train data OverSampling
    if i == cut_i[j]:
        total_X = X_train
        total_Y = Y_train
        j += 1
    else:
        total_X = np.vstack((total_X,X_train))
        total_Y = np.hstack((total_Y,Y_train))
        if i == cut_i[j]-1:
            smote = BorderlineSMOTE()
            X_train_new, Y_train_new = smote.fit_resample(total_X, total_Y)
            nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
            nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
            print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

            scaler1 = MinMaxScaler()
            scaler1.fit(X_train_new)
            X_train_new = scaler1.transform(X_train_new)
             # save dataset (pickle files)

            with open(f'{output_path}/X_train_T{j}.pkl','wb') as f1:
                pickle.dump(X_train_new, f1)
            with open(f'{output_path}/Y_train_T{j}.pkl','wb') as f2:
                pickle.dump(Y_train_new, f2)
            with open(f'{output_path}/scaler_T{j}.pkl','wb') as f5:
                pickle.dump(scaler1, f5)

Finish Oversampling, check to count: Frost 0(17080), Frost 1(17080)
Finish Oversampling, check to count: Frost 0(17179), Frost 1(17179)
Finish Oversampling, check to count: Frost 0(17082), Frost 1(17082)
Finish Oversampling, check to count: Frost 0(17180), Frost 1(17180)
Finish Oversampling, check to count: Frost 0(17087), Frost 1(17087)
Finish Oversampling, check to count: Frost 0(17180), Frost 1(17180)
Finish Oversampling, check to count: Frost 0(17088), Frost 1(17088)
Finish Oversampling, check to count: Frost 0(17181), Frost 1(17181)
Finish Oversampling, check to count: Frost 0(17088), Frost 1(17088)
Finish Oversampling, check to count: Frost 0(17169), Frost 1(17169)
Finish Oversampling, check to count: Frost 0(17088), Frost 1(17088)
Finish Oversampling, check to count: Frost 0(17171), Frost 1(17171)
Finish Oversampling, check to count: Frost 0(17089), Frost 1(17089)
Finish Oversampling, check to count: Frost 0(17171), Frost 1(17171)
Finish Oversampling, check to count: Frost 0(170

In [9]:
# 36 class ver.
# INPUT DATA part

input_path = 'C:/Users/LG/Desktop/frost_data/ver3/ML_input'
input_list = glob.glob(f'{input_path}/**.pkl', recursive=True)
input_iter = len(input_list)
output_path = 'C:/Users/LG/Desktop/frost_data/ver3/SMOTE_BL/36class'
# +all data -> one table

cut_i = range(0,73,2)
j = 0
for i in range(0,input_iter):
    with open(f'{input_path}/train_T{i}.pkl','rb') as f:
        input_data = pickle.load(f)
    X_train = input_data[:,:-2]
    Y_train = input_data[:,-2]
    # Train data OverSampling
    if i == cut_i[j]:
        total_X = X_train
        total_Y = Y_train
        j += 1
    else:
        total_X = np.vstack((total_X,X_train))
        total_Y = np.hstack((total_Y,Y_train))
        if i == cut_i[j]-1:
            smote = BorderlineSMOTE()
            X_train_new, Y_train_new = smote.fit_resample(total_X, total_Y)
            nb_0 = pd.DataFrame(Y_train_new).value_counts().iloc[0]
            nb_1 = pd.DataFrame(Y_train_new).value_counts().iloc[1]
            print("Finish Oversampling, check to count: Frost 0({}), Frost 1({})".format(nb_0, nb_1))

            scaler1 = MinMaxScaler()
            scaler1.fit(X_train_new)
            X_train_new = scaler1.transform(X_train_new)
             # save dataset (pickle files)

            with open(f'{output_path}/X_train_T{j}.pkl','wb') as f1:
                pickle.dump(X_train_new, f1)
            with open(f'{output_path}/Y_train_T{j}.pkl','wb') as f2:
                pickle.dump(Y_train_new, f2)
            with open(f'{output_path}/scaler_T{j}.pkl','wb') as f5:
                pickle.dump(scaler1, f5)

Finish Oversampling, check to count: Frost 0(11351), Frost 1(11351)
Finish Oversampling, check to count: Frost 0(11488), Frost 1(11488)
Finish Oversampling, check to count: Frost 0(11420), Frost 1(11420)
Finish Oversampling, check to count: Frost 0(11353), Frost 1(11353)
Finish Oversampling, check to count: Frost 0(11488), Frost 1(11488)
Finish Oversampling, check to count: Frost 0(11421), Frost 1(11421)
Finish Oversampling, check to count: Frost 0(11356), Frost 1(11356)
Finish Oversampling, check to count: Frost 0(11490), Frost 1(11490)
Finish Oversampling, check to count: Frost 0(11421), Frost 1(11421)
Finish Oversampling, check to count: Frost 0(11356), Frost 1(11356)
Finish Oversampling, check to count: Frost 0(11492), Frost 1(11492)
Finish Oversampling, check to count: Frost 0(11421), Frost 1(11421)
Finish Oversampling, check to count: Frost 0(11359), Frost 1(11359)
Finish Oversampling, check to count: Frost 0(11484), Frost 1(11484)
Finish Oversampling, check to count: Frost 0(114